### ISSUE TITLE
Add abstraction for different tokenizers (in own Module?)

### ISSUE THREAD

**Issue by luzian-hahn** [Modalities/modalities#21]
Right now the only supported tokenizer within the code is the `GPT2TokenizerFast` from `huggingface`.
If we want to support fast tokenizers like the one from tiktoken but also different types, like the one from Llama or own trained ones, which can be useful, when more languages than just english come into play, we need to add another abstraction layer over the existing one.

It should prescribe the essential functionalities we need from it (loadability, encoding, decoding - probably one can get also easy inspiration from the million existing interfaces flying around).

### Tokenizer Module

Finally the question popped up to export this whole effort into an own module, giving users the ability to train own tokenizers without depending on the larger code base in parallel. 

#### Pros:
- Clear Logic Separation between training and preliminary steps
- reduced set of dependencies when training only a tokenizer in preparation for a later training run
- allows other people, not being involved in the training code base to train own tokenizers

#### Cons:
- Larger Over head for parallel maintence, especially regarding Version Management like SemVer
- In theory the same arguments regarding separation could get apply for Dataset preparation like packing and indexing etc.

### Responsibilities of a standalone Tokenizer Module

- [ ] Provision of Abstraction Layer 
- [ ] Customized Tokenizer Training as Feature

**Comment by le1nux** [comment]
integrated via PR #102
