### ISSUE TITLE
feat: Ability to merge different .pbin files into one

### ISSUE THREAD

**Issue by luzian-hahn** [Modalities/modalities#22]
We might reach the point where we have to different datasets prepared as packed Datasets, but want to join them. Instead of merging their source version and running the whole process again, it might be easier to join them on .pbin-format level. 
This means adapting the headers based on the changes to the data section, concatenating the data sections and loading the pickled indices, joining them and pickling them again.

**Comment by mrudat-iais** [comment]
I did my review. Waiting for @luzian-hahn to resolve comments.
