### ISSUE TITLE
Convert checkpoints without usage of FSDP

### ISSUE THREAD

**Issue by rrutmann** [Modalities/modalities#27]
Currently, during the conversion of our checkpoints into HF format, the initial model checkpoint is loaded using FSDP. We should remove this overhead, since FSDP loads the model checkpoint on (memory limited) GPUs, which is not required for the conversion.

**Comment by le1nux** [comment]
@rrutmann we have a checkpoint loading component now that only uses pytorch (without FDSP) see PR #102 

https://github.com/Modalities/modalities/pull/102/files#diff-d6ecdc61a672a0ed7797db6606dbf337c5958244a2c6fad479a0394ede2e266aR14

Does this fix this issue completely already, @rrutmann?

**Comment by mali-git** [comment]
@rrutmann, can we close this issue?
