### ISSUE TITLE
Feat: Improving the registry and dependency injection for hierarchical instantiation

### ISSUE THREAD

**Issue by le1nux** [Modalities/modalities#31]
While integrating Huggingface transformers into modalities, I figured that we need to improve the hierarchical instantiation from the config substantially and rather sooner than later, otherwise extensibility is limited. 

Right now, the instantiation via the registry is flat and we have helper functions in main which reflect the hierarchy. For instance, when we instantiate the optimizer, we instantiate the model first via 
```python
        model: torch.nn.Module = self.resolvers.build_component_by_config(config=config.model)

``` 

and then subsequently we feed in the moder parameters into the optimizer via 
```python
optimizer: torch.optim.Optimizer = self.resolvers.build_component_by_config(
        config=config.optimizer, extra_kwargs=dict(params=wrapped_model.parameters())
)
```

This approach is only feasible for small hierarchies and as long as the components are generic, e.g., if the optimizer always needs an nn.Module object passed. 

The moment when concrete implementations have different dependencies this breaks. For instance, if one special optimizer not only depends on a model but also on another component, then this would be a special case that we would have to reflect/hardcode in our code.

Given these issues, I would suggest we implement hierarchical instantiation within the registry already.

We would call `registry.build(config: AppConfig, component_names: List[str]) -> Dict[str, Any]` to instantiate the components given by `component_names`. Since these components will depend on other components up in the hierarchy, the registry will start instantiating the components without any dependencies. Then we continue the instantiation by injecting the already instantiated components until all components in `component_names` are instantiated. 

Given this setup, we can build arbitrary configs and dependencies, as the registry is capable of the whole instantiation process.

**Comment by luzian-hahn** [comment]
@lllAlexanderlll is your solution from this weeks hackathon solving this? If I got it right, by explicitly specifying type hints, pydantic could not get confused about turning a Config into a different type, than the respective type_hint would expect. Therefore, when having nested configs, a miss configuration is not possible anymore, isn't it?

**Comment by lllAlexanderlll** [comment]
In my tests with a flat config specification it worked to instantiate the correct config and select the config class specified by the type_hint. Also, validation errors were thrown for incorrect configs.

**Comment by luzian-hahn** [comment]
only that I get this right - with "copy_by_value" and "copy_by_reference" you refer to having two components, which require an object of the same type for their initialization and then either requiring a copy of that or a reference (e.g. using the same dataset instance for two situations, while using two different dataloaders, so their iteration is not affected by concurrency issues?)
