### ISSUE TITLE
Add generation abilities to HF model for downstream evaluation

### ISSUE THREAD

**Issue by rrutmann** [Modalities/modalities#46]

**Comment by mrudat-iais** [comment]
PR is [here](https://github.com/Modalities/lm-evaluation-harness/pull/1). Please check. 

We implemented the greedy_until() method. Is that enough or do we also need a generate() ?

**Comment by mali-git** [comment]
@mrudat-iais @rrutmann, what is the status here?

**Comment by mrudat-iais** [comment]
It is done.
