### ISSUE TITLE
Pydantic 3.0 compatibility

### ISSUE THREAD

**Issue by thomaschhh** [Modalities/modalities#57]
https://github.com/Modalities/modalities/blob/d71bceb661b560ee9ccaa2a1ed25a089947d095c/src/modalities/config/config.py#L42

Pydantic's documentation of the function `coint()` is saying

``` 
!!! warning "Discouraged"
        This function is **discouraged** in favor of using
        [`Annotated`](https://docs.python.org/3/library/typing.html#typing.Annotated) with
        [`Field`][pydantic.fields.Field] instead.

        This function will be **deprecated** in Pydantic 3.0.

        The reason is that `conint` returns a type, which doesn't play well with static analysis tools.

```
The same also applies to `confloat()`.

Should we change the relevant lines (to e.g. `Annotated[int, Field(strict=True, gt=0)]` ) in order to be future-proof?

This would also fix the warning that Pylance is throwing `Call expression not allowed in type expression`.

**Comment by lllAlexanderlll** [comment]
Hi Thomas,

good hint, thanks! Max and I will introduce the fix in the `hierarchical_instantiation` branch, as it changes the config.py file quite a bit

**Comment by thomaschhh** [comment]
Sure!
I checked your commit e1dd046 - looks good to me!

**Comment by flxst** [comment]
There were a few more occurrences of `conint` and `confloat`, I replaced them in commit e70f3a0e5742b3e6d4e5e014628fad4fe765ea44. 

However, I wonder if we should introduce TypeAliases like e.g. `IntGt1 = Annotated[int, Field(strict=True, gt=1)]` to make the code more readable.
