### ISSUE TITLE
Feat: Implementation of RMSNorm

### ISSUE THREAD

**Issue by le1nux** [Modalities/modalities#66]
RMSNorm is more compute-efficient in comparison to LayerNorm, as explained in the original paper:
https://openreview.net/pdf?id=SygkZ3MTJE

Due to its benefits, RMSNorm replaces LayerNorm also in LLama 2 for instance. 

The llama 2 implementation can be found here:
https://github.com/facebookresearch/llama/blob/a0a4da8b497c566403941ceec47c2512ecf9dd20/llama/model.py#L34

**Comment by flxst** [comment]
Implemented in #67.
